/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo_2301082009.p280524;

/**
 *
 * @author N I P
 */
public class FromStudentRecord extends javax.swing.JFrame {

    /**
     * Creates new form FromStudentRecord
     */
    public FromStudentRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtMathGrade = new javax.swing.JTextField();
        txtEnglishGrade = new javax.swing.JTextField();
        txtScienceGrade = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtAverage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 31, 16);

        jLabel2.setText("Address");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 70, 16);

        jLabel3.setText("Age");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 90, 21, 16);
        getContentPane().add(txtAddress);
        txtAddress.setBounds(150, 60, 230, 26);
        getContentPane().add(txtName);
        txtName.setBounds(150, 30, 230, 26);

        jLabel6.setText("MathGrade");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 120, 59, 16);

        jLabel7.setText("EnglishGrade");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 150, 69, 16);

        jLabel8.setText("ScienceGrade");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 180, 70, 16);
        getContentPane().add(txtAge);
        txtAge.setBounds(150, 90, 230, 26);

        txtMathGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMathGradeActionPerformed(evt);
            }
        });
        getContentPane().add(txtMathGrade);
        txtMathGrade.setBounds(150, 120, 230, 26);

        txtEnglishGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnglishGradeActionPerformed(evt);
            }
        });
        getContentPane().add(txtEnglishGrade);
        txtEnglishGrade.setBounds(150, 150, 230, 26);
        getContentPane().add(txtScienceGrade);
        txtScienceGrade.setBounds(150, 180, 230, 26);

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        getContentPane().add(btnProses);
        btnProses.setBounds(20, 220, 350, 27);

        jLabel4.setText("Average ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 270, 50, 16);
        getContentPane().add(txtAverage);
        txtAverage.setBounds(150, 270, 230, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMathGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMathGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMathGradeActionPerformed

    private void txtEnglishGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnglishGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnglishGradeActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        pbo_2301082009.p260304.StudentRecord student = new pbo_2301082009.p260304.StudentRecord();
        student.setName(txtName.getText());
        student.setAddress(txtAddress.getText());
        student.setAge(Integer.parseInt(txtAge.getText()));
        student.setMathGrade(Double.parseDouble(txtMathGrade.getText()));
        student.setEnglishGrade(Double.parseDouble(txtEnglishGrade.getText()));
        student.setScienceGrade(Double.parseDouble(txtScienceGrade.getText()));
        txtAverage.setText(student.getAverage() + "");
    }//GEN-LAST:event_btnProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromStudentRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAverage;
    private javax.swing.JTextField txtEnglishGrade;
    private javax.swing.JTextField txtMathGrade;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtScienceGrade;
    // End of variables declaration//GEN-END:variables
}
